# Copyright (c) 2020-present, The kubequery authors
#
# This source code is licensed as defined by the LICENSE file found in the
# root directory of this source tree.
#
# SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

name: Build

on:
  push:
    branches: [ master ]
    tags: [ "**" ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Detect tag
      id: vars
      run: |
        if [[ "$GITHUB_REF" == "refs/heads/master" ]]; then
          echo ::set-output tag=latest
        elif [[ $GITHUB_REF = refs/tags/* ]]; then
          echo ::set-output tag=$(echo $GITHUB_REF | cut -d'/'' -f3)
        else
          echo ::set-output tag=
        fi

    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: make

    - name: FOSSA scan
      uses: fossa-contrib/fossa-action@v1
      with:
        fossa-api-key: ${{ secrets.FOSSA_API_KEY }}

    - name: Build container image
      if: steps.vars.outputs.tag != ''
      run: docker build --build-arg KUBEQUERY_VERSION=${{ steps.vars.outputs.tag }} --file Dockerfile --tag uptycs/kubequery:${{ steps.vars.outputs.tag }} .

    - name: DockerHub login
      uses: docker/login-action@v1
      if: steps.vars.outputs.tag != ''
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: DockerHub push
      uses: docker/build-push-action@v2 || startsWith(github.ref, 'refs/tags/')
      if: steps.vars.outputs.tag != ''
      with:
        push: true
        tags: uptycs/kubequery:${{ steps.vars.outputs.tag }}
