# Copyright (c) 2020-present, The kubequery authors
#
# This source code is licensed as defined by the LICENSE file found in the
# root directory of this source tree.
#
# SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

name: Build

on:
  push:
    branches: [ master ]
    tags: [ "**" ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Detect tag
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: make

    - name: FOSSA scan
      uses: fossa-contrib/fossa-action@v1
      with:
        fossa-api-key: ${{ secrets.FOSSA_API_KEY }}

    - name: Release docker image
      if: startsWith(github.ref, 'refs/tags/')
      run: docker build . --file Dockerfile --tag uptycs/kubequery:${{ steps.vars.outputs.tag }}

    - name: Latest docker image
      if: github.ref == 'refs/heads/master'
      run: docker build . --file Dockerfile --tag uptycs/kubequery:latest
